# Generated by Django 3.2 on 2025-06-08 18:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название категории, к которой относится произведение",
                        max_length=256,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Уникальный фрагмент URL-адреса",
                        unique=True,
                        verbose_name="Слаг",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название жанра, к которому относится произведение",
                        max_length=256,
                        verbose_name="Жанр",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Уникальный фрагмент URL-адреса",
                        unique=True,
                        verbose_name="Слаг",
                    ),
                ),
            ],
            options={
                "verbose_name": ("Жанр",),
                "verbose_name_plural": "Жанры",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="GenreTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="genres",
                        to="reviews.genre",
                        verbose_name="Жанр",
                    ),
                ),
            ],
            options={
                "verbose_name": "Произведение и жанр",
                "verbose_name_plural": "Произведения и жанры",
                "ordering": ("title", "genre"),
            },
        ),
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название произведения",
                        max_length=256,
                        verbose_name="Произведение",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        db_index=True,
                        help_text="Используйте формат для года <YYYY>",
                        validators=[
                            django.core.validators.MinValueValidator(1600),
                            django.core.validators.MaxValueValidator(2025),
                        ],
                        verbose_name="Год",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Краткое содержание произведения",
                        max_length=2000,
                        null=True,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Название категории, к которому относится произведение",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reviews.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "genre",
                    models.ManyToManyField(
                        help_text="Название жанра, к которому относится произведение",
                        related_name="titles",
                        through="reviews.GenreTitle",
                        to="reviews.Genre",
                        verbose_name="Жанр",
                    ),
                ),
            ],
            options={
                "verbose_name": "Произведение",
                "verbose_name_plural": "Произведения",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст отзыва")),
                (
                    "score",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Оценка не может быть меньше 1"
                            ),
                            django.core.validators.MaxValueValidator(
                                10, "Оценка не может быть больше 10"
                            ),
                        ]
                    ),
                ),
                (
                    "pub_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата публикации"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор отзыва",
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="reviews.title",
                        verbose_name="Название произведения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "ordering": ("-pub_date",),
            },
        ),
        migrations.AddField(
            model_name="genretitle",
            name="title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="titles",
                to="reviews.title",
                verbose_name="Произведение",
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст комментария")),
                (
                    "pub_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата публикации"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор комментария",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="reviews.review",
                        verbose_name="Отзыв",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
                "ordering": ("-pub_date",),
            },
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("title", "author"), name="unique_review"
            ),
        ),
    ]
